/* SYNTHETIC DATA ONLY. Run in a fresh SAS session separately from the core fixture.
   Expected IDs 1 2 3. OR branches include people who pass either event criterion.
   Exclusion applies to both branches. Last-index demographics exclude person 6. */
data work.tree_fixture_O;
  length ENROLID YEAR AGE SEQNUM SVCDATE 8 SEX DXVER PROCTYP $1 DX1-DX4 PROC1 $7;
  YEAR=2023;SEX='1';SEQNUM=0;
  do ENROLID=1 to 6;
    AGE=40;DXVER='0';PROCTYP='1';PROC1='';DX1='E119';SVCDATE='15JUN2023'd;SEQNUM+1;output;
    if ENROLID in (1,6) then do;
      SVCDATE='18JUN2023'd;if ENROLID=6 then AGE=17;SEQNUM+1;output;
    end;
    DX1='';AGE=40;SVCDATE='10JUN2023'd;
    if ENROLID in (1,3,6) then do;PROC1='99213';PROCTYP='1';SEQNUM+1;output;end;
    if ENROLID in (2,3,4,5) then do;
      PROC1='J0001';PROCTYP='7';if ENROLID=4 then PROCTYP='1';SEQNUM+1;output;
    end;
    if ENROLID in (3,5) then do;
      PROC1='';DX1='Z850';DXVER='0';if ENROLID=3 then DXVER='9';SEQNUM+1;output;
    end;
  end;
run;
/* Generated by ROGER. MarketScan 2023. SAS 9.4.
   Run in your approved SAS environment. Review the definition and mappings.
   Last matching event in the index window is selected BEFORE later filters.
   Ties use source table letter then SEQNUM. One row per ENROLID.
   Distinct service days determine repeated-event criteria.
   This program has not been executed by the browser.
   Mappings supplied. Verify they identify the intended database and edition.
*/
options errorabend;
/* Assign your input librefs before running, or add a LIBNAME statement here. */
/* Outputs will be created in WORK for this SAS session. */
%let map_O=WORK.TREE_FIXTURE_O;
%let map_S=;
%let map_I=;
%let map_F=;
%let map_D=;
%let map_T=;
%let age_min=18;
%let age_max=64;
%let sex=ALL;
%let enrollment=0;
%let baseline=90;
%let followup=0;
%let gap=0;
%let rx=0;
%let extract_before=90;
%let extract_after=0;
%let outputs=;
%let outlib=WORK;
%let index_order=LAST;
%let advanced_logic=1;
%let index_start=%sysfunc(inputn(20230601,yymmdd8.));
%let index_end=%sysfunc(inputn(20230630,yymmdd8.));

data work._rg_definition;
  length name $120 schema_id $40 family $4 edition $1 input_path output_path $250;
  name='Synthetic nested tree and last index check';
  schema_id='marketscan-ccae-mdcr-2023-v1';
  family='CCAE';
  edition='A';
  data_year=2023;
  length index_order $5 logic_json $12000;
  index_order='LAST';
  logic_json='{"id":"g0","op":"AND","children":[{"id":"g1","op":"OR","children":[0,1]},2]}';
  created_at=datetime();
  format created_at datetime20. index_start index_end yymmdd10.;
  index_start=&index_start;
  index_end=&index_end;
  input_path='';
  output_path='';
  age_min=18;
  age_max=64;
  sex='ALL';
  enrollment=0;
  baseline=90;
  followup=0;
  gap=0;
  rx=0;
  extract_before=90;
  extract_after=0;
  outputs='';
  outlib='WORK';
  length map_O $41; map_O='WORK.TREE_FIXTURE_O';
  length map_S $41; map_S='';
  length map_I $41; map_I='';
  length map_F $41; map_F='';
  length map_D $41; map_D='';
  length map_T $41; map_T='';
run;
data work._rg_rules;
  length rule_id min_days lower_day upper_day 8 mode $7 domain $5 sources $12;
  infile datalines4 dlm='|' dsd truncover;
  input rule_id mode :$7. domain :$5. sources :$12. min_days lower_day upper_day;
datalines4;
1|INDEX|DX|O|1|0|0
2|INCLUDE|CPT|O|1|-30|0
3|INCLUDE|HCPCS|O|1|-30|0
4|EXCLUDE|DX|O|1|-30|0
;;;;
run;
data work._rg_codes;
  length rule_id 8 code $11 match_type $6;
  infile datalines4 dlm='|' dsd truncover;
  input rule_id code :$11. match_type :$6.;
datalines4;
1|E11|PREFIX
2|99213|EXACT
3|J0001|EXACT
4|Z85|PREFIX
;;;;
run;

%macro rg_apply_logic;
  data work._rg_cohort;
    set work._rg_cohort;
    if ((_rg_pass_2=1 OR _rg_pass_3=1) AND _rg_pass_4=1);
    drop _rg_pass_:;
  run;
%mend;

/* ROGER cohort engine 0.2.0. SAS 9.4.
   Input mappings use the 2023 Commercial/Medicare data dictionary.
   Work tables beginning _rg_ are reserved for this run.
   Claims and enrollment remain in SAS. The browser supplies definitions only. */

%macro rg_require(ds, vars, types);
  %local handle j variable position expected rc;
  %let handle=%sysfunc(open(&ds,i));
  %if &handle=0 %then %do;
    %put ERROR: ROGER cannot open &ds.. Assign the input library and table mappings.;
    %abort cancel;
  %end;
  %do j=1 %to %sysfunc(countw(&vars));
    %let variable=%scan(&vars,&j);
    %let expected=%scan(&types,&j);
    %let position=%sysfunc(varnum(&handle,&variable));
    %if &position=0 %then %do;
      %let rc=%sysfunc(close(&handle));
      %put ERROR: ROGER expected &variable in &ds.. Check the 2023 schema.;
      %abort cancel;
    %end;
    %if %sysfunc(vartype(&handle,&position)) ne &expected %then %do;
      %let rc=%sysfunc(close(&handle));
      %put ERROR: ROGER found an unexpected type for &variable in &ds..;
      %abort cancel;
    %end;
  %end;
  %let rc=%sysfunc(close(&handle));
%mend;

%macro rg_checkpoint(label);
  %if &syserr > 4 or &syscc > 4 %then %do;
    %put ERROR: ROGER stopped after &label.. Review the SAS log.;
    %abort cancel;
  %end;
%mend;

%macro rg_count(step, label);
  proc sql;
    insert into work._rg_attrition (step,criterion,remaining)
    select &step, "&label", count(*) from work._rg_cohort;
  quit;
  %rg_checkpoint(attrition);
%mend;

%macro rg_events(rule_id, domain, sources);
  %local k table ds dt fields fieldtypes j filter;
  data work._rg_events;
    length ENROLID event_date AGE SEQNUM 8 SEX source $1 code $11;
    stop;
  run;
  %do k=1 %to %sysfunc(countw(&sources));
    %let table=%scan(&sources,&k);
    %let ds=&&map_&table;
    %let dt=SVCDATE;
    %if &table=I %then %let dt=ADMDATE;
    %let filter=1;
    %if &domain=DX %then %do;
      %rg_require(&ds,DXVER,C);
      %let filter=DXVER='0';
      %let fields=DX1 DX2 DX3 DX4;
      %if &table=S %then %let fields=PDX DX1 DX2 DX3 DX4;
      %if &table=F %then %let fields=DX1 DX2 DX3 DX4 DX5 DX6 DX7 DX8 DX9;
      %if &table=I %then %let fields=PDX DX1 DX2 DX3 DX4 DX5 DX6 DX7 DX8 DX9 DX10 DX11 DX12 DX13 DX14 DX15;
    %end;
    %else %if &domain=NDC %then %let fields=NDCNUM;
    %else %if &domain=DRG %then %let fields=DRG;
    %else %if &domain=PCS and &table=I %then %do;
      %let fields=PROC1 PROC2 PROC3 PROC4 PROC5 PROC6 PROC7 PROC8 PROC9 PROC10 PROC11 PROC12 PROC13 PROC14 PROC15;
    %end;
    %else %do;
      %let fields=PROC1;
      %rg_require(&ds,PROCTYP,C);
      %if &domain=CPT %then %let filter=PROCTYP='1';
      %else %if &domain=PCS %then %let filter=PROCTYP='0';
      %else %let filter=PROCTYP='7';
    %end;
    %let fieldtypes=;
    %do j=1 %to %sysfunc(countw(&fields));
      %if &domain=DRG %then %let fieldtypes=&fieldtypes N;
      %else %let fieldtypes=&fieldtypes C;
    %end;
    %rg_require(&ds,ENROLID &dt AGE SEX SEQNUM YEAR &fields,N N N C N N &fieldtypes);
    data work._rg_matching;
      length ENROLID event_date AGE SEQNUM 8 SEX source $1 code _value $11 match_type $6;
      /* Match during the scan so nonmatching diagnosis rows never reach WORK. */
      if _n_=1 then do;
        declare hash selected(dataset:"work._rg_codes(where=(rule_id=&rule_id))");
        selected.defineKey('code','match_type');
        selected.defineDone();
        call missing(code,match_type);
      end;
      set &ds;
      where YEAR=2023 and &dt >= '01JAN2023'd and &dt <= '31DEC2023'd and (&filter);
      if missing(ENROLID) or missing(&dt) then delete;
      event_date=&dt;
      source="&table";
      %if &domain=DRG %then %do;
        array codes {*} &fields;
      %end;
      %else %do;
        array codes {*} $ &fields;
      %end;
      do _j=1 to dim(codes);
        %if &domain=DRG %then %do;
          if missing(codes[_j]) or codes[_j] ne int(codes[_j]) or codes[_j]<0 or codes[_j]>999 then continue;
          _value=put(codes[_j],z3.);
        %end;
        %else %do;
          _value=compress(upcase(strip(codes[_j])),'. ');
        %end;
        /* Admission procedure fields can mix systems. PCS has seven characters. */
        %if &domain=PCS %then %do;
          if not prxmatch('/^[0-9A-HJ-NP-Z]{7}$/',strip(_value)) then continue;
        %end;
        if not missing(_value) then do;
          code=_value;
          match_type='EXACT';
          _match=(selected.check()=0);
          match_type='PREFIX';
          do _prefix=1 to lengthn(_value) while (not _match);
            code=substr(_value,1,_prefix);
            _match=(selected.check()=0);
          end;
          if _match then do;
            code=_value;
            output;
            leave;
          end;
        end;
      end;
      keep ENROLID event_date AGE SEX SEQNUM source code;
    run;
    %rg_checkpoint(reading &table);
    proc append base=work._rg_events data=work._rg_matching;
    run;
    %rg_checkpoint(appending events);
  %end;
%mend;

%macro roger_cut;
  %local n_rules rid domain sources mode days lower upper k table ds dt;
  %if %sysfunc(libref(&outlib)) ne 0 %then %do;
    %put ERROR: Assign output library &outlib before running ROGER.;
    %abort cancel;
  %end;
  /* Fail before writing any output from a previous run. */
  %if %sysfunc(exist(&outlib..cohort)) or %sysfunc(exist(&outlib..attrition)) or
      %sysfunc(exist(&outlib..definition)) or %sysfunc(exist(&outlib..rules)) or
      %sysfunc(exist(&outlib..code_sets)) %then %do;
    %put ERROR: ROGER output tables already exist. Use a fresh output library.;
    %abort cancel;
  %end;
  %do k=1 %to %sysfunc(countw(&outputs));
    %let table=%scan(&outputs,&k);
    %if %sysfunc(exist(&outlib..cut_&table)) %then %do;
      %put ERROR: ROGER output cut_&table already exists. Use a fresh output library.;
      %abort cancel;
    %end;
  %end;

  data work._rg_attrition;
    length step remaining 8 criterion $160;
    stop;
  run;
  proc sql noprint;
    select domain,sources into :domain trimmed,:sources trimmed
      from work._rg_rules where rule_id=1;
    select count(*) into :n_rules trimmed from work._rg_rules;
  quit;
  %rg_events(1,&domain,&sources);
  proc sort data=work._rg_events(where=(event_date >= &index_start and event_date <= &index_end))
    out=work._rg_index;
    by ENROLID %if &index_order=LAST %then %do; descending %end; event_date source SEQNUM;
  run;
  data work._rg_cohort;
    set work._rg_index;
    by ENROLID;
    if first.ENROLID;
    index_date=event_date;
    index_source=source;
    index_seqnum=SEQNUM;
    format index_date yymmdd10.;
    keep ENROLID index_date AGE SEX index_source index_seqnum;
  run;
  %rg_checkpoint(index event);
  %rg_count(1,&index_order matching index event);
  data work._rg_cohort;
    set work._rg_cohort;
    if missing(AGE) or AGE < &age_min or AGE > &age_max then delete;
    %if &sex ne ALL %then %do;
      if SEX ne "&sex" then delete;
    %end;
  run;
  %rg_count(2,Demographic requirements);

  %if &enrollment=1 %then %do;
    %rg_require(&map_T,ENROLID DTSTART DTEND YEAR RX,N N N N C);
    proc sql;
      create table work._rg_intervals as
      select c.ENROLID,c.index_date,
             max(e.DTSTART,c.index_date-&baseline) as span_start,
             min(e.DTEND,c.index_date+&followup) as span_end
      from work._rg_cohort c inner join &map_T e
        on c.ENROLID=e.ENROLID
      where e.YEAR=2023 and not missing(e.DTSTART) and not missing(e.DTEND)
        and e.DTSTART <= e.DTEND
        and e.DTSTART <= c.index_date+&followup
        and e.DTEND >= c.index_date-&baseline
        %if &rx=1 %then %do; and e.RX='1' %end;
      order by ENROLID,span_start,span_end;
    quit;
    %rg_checkpoint(enrollment intervals);
    data work._rg_eligible;
      set work._rg_intervals;
      by ENROLID;
      retain covered_start covered_end max_gap;
      if first.ENROLID then do;
        covered_start=span_start;
        covered_end=span_end;
        max_gap=0;
      end;
      else do;
        max_gap=max(max_gap,span_start-covered_end-1);
        covered_end=max(covered_end,span_end);
      end;
      if last.ENROLID and covered_start <= index_date-&baseline
        and covered_end >= index_date+&followup and max_gap <= &gap then output;
      keep ENROLID;
    run;
    proc sql;
      create table work._rg_next as select c.* from work._rg_cohort c
      inner join work._rg_eligible e on c.ENROLID=e.ENROLID;
    quit;
    data work._rg_cohort; set work._rg_next; run;
    %rg_checkpoint(enrollment eligibility);
    %rg_count(3,Enrollment requirements);
  %end;

  %do rid=2 %to &n_rules;
    proc sql noprint;
      select domain,sources,mode,min_days,lower_day,upper_day
        into :domain trimmed,:sources trimmed,:mode trimmed,:days trimmed,:lower trimmed,:upper trimmed
        from work._rg_rules where rule_id=&rid;
    quit;
    %rg_events(&rid,&domain,&sources);
    proc sql;
      create table work._rg_hitcounts as
      select c.ENROLID,count(distinct e.event_date) as hit_days
      from work._rg_cohort c left join work._rg_events e
        on c.ENROLID=e.ENROLID and e.event_date >= c.index_date+&lower
        and e.event_date <= c.index_date+&upper
      group by c.ENROLID;
      create table work._rg_next as select c.*
      %if &advanced_logic=1 %then %do;
        , (h.hit_days %if &mode=INCLUDE %then %do; >= %end; %else %do; < %end; &days) as _rg_pass_&rid
      %end;
      from work._rg_cohort c
      inner join work._rg_hitcounts h on c.ENROLID=h.ENROLID
      %if &advanced_logic=0 %then %do;
        %if &mode=INCLUDE %then %do; where h.hit_days >= &days %end;
        %else %do; where h.hit_days < &days %end;
      %end;
      ;
    quit;
    data work._rg_cohort; set work._rg_next; run;
    %rg_checkpoint(rule &rid);
    %if &advanced_logic=0 %then %rg_count(%eval(&rid+2),&mode rule &rid - &domain);
  %end;

  %if &advanced_logic=1 %then %do;
    %rg_apply_logic;
    %rg_checkpoint(condition tree);
    %rg_count(%eval(&n_rules+3),Combined AND OR condition tree);
  %end;

  /* Prepare all extracts in WORK before creating the delivery datasets. */
  %do k=1 %to %sysfunc(countw(&outputs));
    %let table=%scan(&outputs,&k);
    %let ds=&&map_&table;
    %let dt=SVCDATE;
    %if &table=I %then %let dt=ADMDATE;
    %if &table=T %then %let dt=DTSTART;
    %rg_require(&ds,ENROLID &dt YEAR,N N N);
    %if &table=T %then %rg_require(&ds,DTEND,N);
    proc sql;
      create table work._rg_cut_&table as
      select e.*,c.index_date from &ds e inner join work._rg_cohort c
        on e.ENROLID=c.ENROLID
      where e.YEAR=2023 and not missing(e.&dt)
      %if &table=T %then %do;
        and not missing(e.DTEND) and e.DTSTART <= e.DTEND
        and e.DTSTART <= c.index_date+&extract_after
        and e.DTEND >= c.index_date-&extract_before
      %end;
      %else %do;
        and e.&dt >= c.index_date-&extract_before
        and e.&dt <= c.index_date+&extract_after
      %end;
      ;
    quit;
    %rg_checkpoint(extracting &table);
  %end;
  data &outlib..cohort; set work._rg_cohort; run;
  data &outlib..attrition;
    set work._rg_attrition;
    retain initial previous;
    if _n_=1 then do; initial=remaining; previous=remaining; end;
    removed=previous-remaining;
    if initial > 0 then proportion_remaining=remaining/initial;
    previous=remaining;
    drop previous initial;
  run;
  data &outlib..definition; set work._rg_definition; run;
  data &outlib..rules; set work._rg_rules; run;
  data &outlib..code_sets; set work._rg_codes; run;
  %do k=1 %to %sysfunc(countw(&outputs));
    %let table=%scan(&outputs,&k);
    data &outlib..cut_&table; set work._rg_cut_&table; run;
  %end;
  %rg_checkpoint(delivery);
  title 'ROGER cohort attrition';
  proc print data=&outlib..attrition noobs; run;
  title;
  %put NOTE: ROGER completed. Cohort and selected extracts are in &outlib..;
%mend;


%macro rg_check_mappings;
  %if %length(%superq(map_O))=0 %then %do;
    %put ERROR: Set map_O to the actual SAS dataset before running.;
    %abort cancel;
  %end;
%mend;
%rg_check_mappings;
%roger_cut;

%macro assert_tree;
  %local ids bad stages;
  proc sql noprint;
    select ENROLID into :ids separated by ' ' from work.cohort order by ENROLID;
    select count(*) into :bad trimmed from work.cohort
      where (ENROLID=1 and index_date ne '18JUN2023'd)
         or (ENROLID ne 1 and index_date ne '15JUN2023'd);
    select remaining into :stages separated by ' ' from work.attrition order by step;
  quit;
  %if "%superq(ids)" ne "1 2 3" or &bad ne 0 or "%superq(stages)" ne "6 5 3" %then %do;
    %put ERROR: Nested tree or last-index check failed. ids=&ids bad=&bad stages=&stages;
    %abort cancel;
  %end;
  %rg_checkpoint(nested tree assertions);
  %put NOTE: ROGER NESTED TREE CHECK PASSED.;
%mend;
%assert_tree;
